repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: fixtures
    args: [--check, --config=pyproject.toml]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    additional_dependencies: [black, types-pkg_resources, types-setuptools, types-toml]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
